version: "3"

services:
  db:
    image: postgres
    container_name: api-itec-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "090821"
      POSTGRES_DB: "itecdb"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

