version: "3"

services:
  api-itec-content:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
        - "8080:8080"
    restart: always
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/api-itec-content-db
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=090821
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
        - SPRING_JPA_SHOW_SQL=true
        - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
        - SPRING_JPA_PROPERTIES_HIBERNATE_USE_SQL_COMMENTS=true
        - SERVER_PORT=8080
    networks:
        - spring-boot-postgres-network
    depends_on:
        - postgres-service
  db:
    image: postgres
    container_name: api-itec-content-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "090821"
      POSTGRES_DB: "api-itec-content-db"
    ports:
      - "5432:5432"
    networks:
      - spring-boot-postgres-network
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d/init.sql
networks:
  spring-boot-postgres-network:
    driver: bridge
